<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_login-email</name>
   <tag></tag>
   <elementGuidId>9c37beea-a034-4eea-88d3-2bc0524bcfaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d0a9d84-6719-4de3-a642-443592828efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-email</value>
      <webElementGuid>0670361b-f09e-4356-a2ea-9e3a4b01d1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-email</value>
      <webElementGuid>22845770-57bf-4384-a9a1-b3e9351f1dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c060fb02-8a9f-414b-9bf9-b9412e4ee0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fee6d7bd-7ce5-4a30-a843-e9e711c42163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b04f85e-92c3-4523-af0e-31e69a01d9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-email&quot;)</value>
      <webElementGuid>e6cece4c-bce5-4ae2-9f23-fdc7845c92bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-email']</value>
      <webElementGuid>5a06ad43-3c5d-4db6-88ea-611fb145c8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__47']/div/span/input</value>
      <webElementGuid>8f40b817-1015-4f1b-82a6-a257986f9ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9ff28dc4-568d-49b9-b20d-843d4f91d8cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-email' and @name = 'login-email' and @type = 'text' and @placeholder = 'email']</value>
      <webElementGuid>eadb6425-b5dc-441e-a60e-89896b66ff13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
