<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Build Project</name>
   <tag></tag>
   <elementGuidId>e4657c5d-e553-411c-8204-0ce26272735c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnGoalOneStep</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnGoalOneStep']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e287adc-bea1-49f4-8963-5161d8532d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGoalOneStep</value>
      <webElementGuid>05494c86-c26a-4369-b35d-1efb54c84980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1b6faad-94a3-48e3-a020-335cf2b277a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>55bfc91d-71e2-49ab-94b6-d587a25d8d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Build Project </value>
      <webElementGuid>e2eaddef-f10a-4ad9-8d7b-da7f9c89941a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGoalOneStep&quot;)</value>
      <webElementGuid>6a02e642-6bdc-4902-a8e8-fa75b9807f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnGoalOneStep']</value>
      <webElementGuid>60f85f41-cd70-4eaf-adc7-78bc0753cb73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='addProjModal___BV_modal_footer_']/button[2]</value>
      <webElementGuid>2788f2f6-35f3-4571-b8bf-e28b4d42fe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>c34a7e26-e96c-43e7-8cfd-5a01fc609376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell your products after collecting leads with a squeeze page.'])[1]/following::button[2]</value>
      <webElementGuid>754af40f-fd37-4898-98ce-aece79e59813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Build Project']/parent::*</value>
      <webElementGuid>e4fb6f1f-442b-4891-a031-de6290b277fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]</value>
      <webElementGuid>e6a034cf-5eec-43b6-aa52-50e931cf0939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnGoalOneStep' and @type = 'button' and (text() = ' Build Project ' or . = ' Build Project ')]</value>
      <webElementGuid>63dbc133-b610-4f3b-8079-66817541ca22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
