<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>728d0b84-bc69-4b7b-bac8-c60397f3324f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sgi_707']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ae24a9a-bb86-4bb1-be23-b62c5a3e414e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.landingly.com//TemplateFiles/Optin/Thankyou/AOptin/_template_files/img_20221013235808994.png</value>
      <webElementGuid>1debde5c-6966-4650-9489-219f74c7ce43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-link</name>
      <type>Main</type>
      <value>#no-link</value>
      <webElementGuid>447853ee-7ec5-4c6d-9d2f-4060cb949e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sgi_707&quot;)/img[1]</value>
      <webElementGuid>622863e1-0be3-4580-8c0b-3da5e669e776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sgi_707']/img</value>
      <webElementGuid>1a5464f5-8232-423d-8e92-d6214a11b8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://api.landingly.com//TemplateFiles/Optin/Thankyou/AOptin/_template_files/img_20221013235808994.png')]</value>
      <webElementGuid>f8716dd2-ecb0-476b-8bd9-dafd240c920b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>3d81dfa8-9d5e-4eea-9f24-d232baafbf76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.landingly.com//TemplateFiles/Optin/Thankyou/AOptin/_template_files/img_20221013235808994.png']</value>
      <webElementGuid>37f52521-e814-4030-8d6c-61b588b10048</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
