<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Use This</name>
   <tag></tag>
   <elementGuidId>a8e330cd-208a-4825-b739-c7105467f2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.mr-1.btn-outline-primary.templates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[3]/div/section/div/div[3]/div/div/div/div/div/div[2]/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>702183bf-aaed-4d50-8a12-4dfe68f8cde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-userstepid</name>
      <type>Main</type>
      <value>40958</value>
      <webElementGuid>82c737ce-060f-4ce1-bb32-973cb8bcc353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currenttabid</name>
      <type>Main</type>
      <value>40958</value>
      <webElementGuid>d86a7a2e-3313-4f1c-acb9-f57090dd27c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aff7619b-084e-4a18-86e5-b6edf4f7913c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parentfolder</name>
      <type>Main</type>
      <value>Thankyou</value>
      <webElementGuid>fbc178f4-b4dc-4c71-9d15-dee59c54e7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mainfolder</name>
      <type>Main</type>
      <value>Optin</value>
      <webElementGuid>adcd161e-1806-4085-9ffb-026f2ccd1907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-childfolder</name>
      <type>Main</type>
      <value>AOptin</value>
      <webElementGuid>31ad98ba-ba52-4a33-ba5a-ac87c3b353ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatetypeid</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>8a52e293-034c-40ef-8d3c-97c0aa692955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-funnelid</name>
      <type>Main</type>
      <value>40481</value>
      <webElementGuid>51e31b19-0b37-4d99-837e-3b42f3a608eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatefilename</name>
      <type>Main</type>
      <value>Template.html</value>
      <webElementGuid>51da795c-2663-4ff6-946e-67061c635b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>08771775-8266-4f5b-ab51-156ca2d15b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c269167f-abc0-41a8-9d42-b5f12adf3ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>6f71c3ca-8a1b-43a8-bb51-64b2456ae849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-1 btn-outline-primary templates</value>
      <webElementGuid>56038b17-9e91-40c1-b9a7-9ab9ae2b50ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Use This</value>
      <webElementGuid>752eee9a-beb3-4dcd-85fb-f358e16934bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vertical-layout h-100 vertical-menu-modern menu-expanded navbar-floating footer-static&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content-body&quot;]/section[1]/div[@class=&quot;b-overlay-wrap position-relative loaderPreview&quot;]/div[3]/div[@class=&quot;row match-height&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;custom-col-6 col-lg-4&quot;]/div[@class=&quot;card shadow-none&quot;]/div[@class=&quot;row text-center mx-0&quot;]/div[@class=&quot;border-top d-flex align-items-between flex-column py-1 col-12&quot;]/h3[@class=&quot;font-weight-bolder mb-0&quot;]/a[@class=&quot;btn mr-1 btn-outline-primary templates&quot;]</value>
      <webElementGuid>f853d513-a784-4fe9-9fe6-a94a3e0b243d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[3]/div/section/div/div[3]/div/div/div/div/div/div[2]/div/h3/a</value>
      <webElementGuid>a46d9e1f-463c-45fe-9de4-f972a00c2336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new optin project'])[1]/following::a[5]</value>
      <webElementGuid>628f693d-822c-4178-97ca-533b595e783e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::a[5]</value>
      <webElementGuid>514a3247-49f5-4a6a-84ba-b1e025b71c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::a[1]</value>
      <webElementGuid>2c57b3ab-fcba-4a50-9d73-af0e3697492b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>d793ddc7-cf24-4692-adc2-47186f079740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>ef87f50c-d949-4d09-9ddc-800c159c5ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Use This' or . = 'Use This')]</value>
      <webElementGuid>5081eea5-bffd-472a-8807-937aadd197f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
