<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Build Project</name>
   <tag></tag>
   <elementGuidId>02493ffc-7c33-4d9e-8c51-41d3b13fd4ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnGoalOneStep</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnGoalOneStep']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cec1c6c3-18a4-4c17-bfcc-529e6bb4705a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGoalOneStep</value>
      <webElementGuid>3d371249-ccd8-4a6e-abcd-62e5acbf041d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6ec96f3-060b-473d-937e-a30ed5a1ebde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>a559db4d-e491-4842-8283-a1b43621c9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Build Project </value>
      <webElementGuid>0ea04766-7dab-4bc4-a6f2-a9f8172db29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGoalOneStep&quot;)</value>
      <webElementGuid>f9ad9e0a-6717-4262-92fd-a145218e3d33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnGoalOneStep']</value>
      <webElementGuid>357ed3c7-a207-4914-9adc-ce23e85fdbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='addProjModal___BV_modal_footer_']/button[2]</value>
      <webElementGuid>87f486bc-d699-4930-a9d1-46266063dbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>1d5ff899-1e36-4b06-9f72-2a91860b942e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell your products after collecting leads with a squeeze page.'])[1]/following::button[2]</value>
      <webElementGuid>0e6e51bf-a6dd-491e-94fb-0f9adb2c9ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Build Project']/parent::*</value>
      <webElementGuid>9b87debc-441f-462f-94db-687bd2a39689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]</value>
      <webElementGuid>5fcc3043-05d2-4ee1-a311-ce64aa6b8503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnGoalOneStep' and @type = 'button' and (text() = ' Build Project ' or . = ' Build Project ')]</value>
      <webElementGuid>cebb8aa5-2b51-41a4-8194-de301f1b4219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
