<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ProjectName</name>
   <tag></tag>
   <elementGuidId>7b0fbf69-e350-4b47-ab5e-cc144f82b041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProjectName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProjectName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>598a4022-b1e1-4a5f-aca5-016883a4bbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProjectName</value>
      <webElementGuid>9b8d6953-24b9-48b6-b2b7-42379a21911f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2961e650-aa6f-49ae-b251-2e2c6ec19a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Project Name</value>
      <webElementGuid>7e8ba746-f157-4557-a525-4ddc6fb2c95f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cac1613e-23d4-4cc2-b313-d23c5d758c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProjectName&quot;)</value>
      <webElementGuid>ad75740b-c8ba-49cf-ae80-a7887956154d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProjectName']</value>
      <webElementGuid>5ff35707-0bb0-49f2-89bb-c5c4901b0fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__265']/div/span/input</value>
      <webElementGuid>bce5f2db-8571-4eb4-a020-da95787789db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a1ed3734-1245-4455-83d2-cd3730d21fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProjectName' and @type = 'text' and @placeholder = 'Please Enter Project Name']</value>
      <webElementGuid>db695ccf-a4de-4eed-a561-77329dc2f873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
