<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Profile_feather feather-moon</name>
   <tag></tag>
   <elementGuidId>44b8308c-932f-4b80-863b-2142c419e5fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-moon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div/nav/div/ul[2]/li/a//*[name()='svg' and @class='feather feather-moon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>3b7bdd28-3315-4830-a74f-d4cb76a43f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>dccba407-021a-420e-b51e-1d5aa026c545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>21px</value>
      <webElementGuid>a7bbf40f-5b8e-42c5-9a31-26e853c379f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>21px</value>
      <webElementGuid>5de3f8be-4834-42ff-b8f4-a1861278e58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>a1a79240-2900-42b5-a5cf-cd516bbec0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1a27dcc7-5948-4a52-8c18-ac3902077a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>c18ce6ee-5d88-4cd1-9b01-6b297d9da5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d0cd41e8-f3c9-4fee-8a71-5304b5027a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>d9a13cf8-7275-47a1-99f2-1a4bcc991b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>c304c8af-d886-44a0-a9a3-21c87bacddfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-moon</value>
      <webElementGuid>92e91dd6-c443-497d-992b-e04741c023d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vertical-layout h-100 vertical-menu-modern menu-expanded navbar-floating footer-static&quot;]/nav[@class=&quot;navbar header-navbar navbar navbar-shadow align-items-center navbar-light navbar-expand floating-nav&quot;]/div[@class=&quot;navbar-container d-flex content align-items-center&quot;]/ul[@class=&quot;navbar-nav nav align-items-center ml-auto&quot;]/li[@class=&quot;nav-item d-none d-lg-block&quot;]/a[@class=&quot;nav-link&quot;]/svg[@class=&quot;feather feather-moon&quot;]</value>
      <webElementGuid>5008d4a0-c688-49b9-a258-2bedb7108187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>2af6cc40-315d-4afe-896d-4d4965779838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>da10425a-55aa-4531-b75b-fa06d9d46813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
