<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Profile_feather feather-sun</name>
   <tag></tag>
   <elementGuidId>de9ac7f5-3a2f-48cb-b05e-0c457235d721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-sun</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[2]/div/nav/div/ul[2]/li/a//*[name()='svg' and @class='feather feather-sun']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b3a16e62-693c-4004-a15c-da39d2e6cf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>8add5c99-3ce5-4bdc-a5e2-23181f321256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>21px</value>
      <webElementGuid>819273ab-7b26-475d-8d57-9c82e041be06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>21px</value>
      <webElementGuid>6bb41586-b7dd-4ccb-9d0c-5f008ea6eb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>724436a6-28a0-4612-82a0-61cb028cc24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>f741cb1a-cac4-4ad1-a0cc-0e668aa7685e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>e1c4519d-53e6-4352-a1c3-de07c6c462e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2ae30e27-ce19-4977-8c0a-c5633295df07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>f5a05101-9dcf-4ac9-86bd-b4409d68250e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>1f90e3b7-c46b-4892-a7be-086483ce5e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-sun</value>
      <webElementGuid>c4e25207-5380-4b43-ac86-74185c8fd7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vertical-layout h-100 vertical-menu-modern menu-expanded navbar-floating footer-static&quot;]/nav[@class=&quot;navbar header-navbar navbar navbar-shadow align-items-center navbar-light navbar-expand floating-nav&quot;]/div[@class=&quot;navbar-container d-flex content align-items-center&quot;]/ul[@class=&quot;navbar-nav nav align-items-center ml-auto&quot;]/li[@class=&quot;nav-item d-none d-lg-block&quot;]/a[@class=&quot;nav-link&quot;]/svg[@class=&quot;feather feather-sun&quot;]</value>
      <webElementGuid>553a9b9c-1c87-42a0-8a00-f516d219575f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>512c07b3-068c-445e-9810-daa9bba2ce13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>f56ac24a-f4fb-4a81-8789-6ac591e426e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
