<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect - Copy</name>
   <tag></tag>
   <elementGuidId>ee79a9d1-a6e3-4880-bfc0-df867c32056b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-archive > rect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@class='rounded']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>11fd3f87-c49e-49d3-b063-9486b2948202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>10626ac9-0de4-45ab-acf0-b02eeb2adc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e9625c3a-8757-4efa-bbc7-604241d9a57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>39ac8517-03d1-4d56-8c57-1b5cd7b16e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>405b89f0-9c0f-4f84-9ecb-89ead2c3f3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__124&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-aside align-self-start&quot;]/a[@class=&quot;user-profile&quot;]/span[@class=&quot;remove-icon&quot;]/svg[@class=&quot;feather feather-archive&quot;]/rect[1]</value>
      <webElementGuid>d23f7a28-8722-4076-aee1-f5a8008d659e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
