<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect - Copy</name>
   <tag></tag>
   <elementGuidId>ee79a9d1-a6e3-4880-bfc0-df867c32056b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[name()='svg' and @class='feather feather-archive']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-archive > rect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>452f3f56-c680-4ac6-8e1e-4aade86e678d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d19d413a-f4fa-4b65-9686-f33c30a4127f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a8d35f1a-9392-44ad-8072-2d764d50ad60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>f3f49ddf-5897-4357-a3ca-7658ae007187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>48393c15-776e-4fd9-aac4-2e0b8d880fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__124&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;media&quot;]/div[@class=&quot;media-aside align-self-start&quot;]/a[@class=&quot;user-profile&quot;]/span[@class=&quot;remove-icon&quot;]/svg[@class=&quot;feather feather-archive&quot;]/rect[1]</value>
      <webElementGuid>e16f100c-bc07-4bec-ae88-385765932a86</webElementGuid>
   </webElementProperties>
</WebElementEntity>
