<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b7910f29-6261-452b-8b0e-1112a77e05e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navbarimage']/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;avatar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13366c43-e279-4c2c-bd62-4723317bf370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/3408640b-defb-4567-8249-072c08ff3ec1.png</value>
      <webElementGuid>6fbf62c8-84c8-46fd-aa90-f7c80cf7742c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>11faefbc-eff8-427a-a6b3-55dabeff6dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarimage&quot;)/span[@class=&quot;b-avatar-img&quot;]/img[1]</value>
      <webElementGuid>42f19130-98d8-4d0f-ab31-f5d6da22b239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbarimage']/span/img</value>
      <webElementGuid>8847f076-b060-45f7-bc7c-ee2fc89214e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>00e6af1e-8932-40a5-a18e-f20fdd40ef68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>a6ac3a83-9673-4e1a-aa92-f3fa01264823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/3408640b-defb-4567-8249-072c08ff3ec1.png' and @alt = 'avatar']</value>
      <webElementGuid>62c1614d-ed9d-43be-838f-e0bec2b3c3a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
