<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Use This</name>
   <tag></tag>
   <elementGuidId>acc49445-fe14-48bf-a409-62167de74df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.mr-1.btn-outline-primary.templates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/div/div/div[2]/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bba1a034-d8e8-4677-be20-f990c6c4abab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-userstepid</name>
      <type>Main</type>
      <value>40965</value>
      <webElementGuid>c1ef8a5d-21db-43fb-b69f-6f3d7b6e99e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currenttabid</name>
      <type>Main</type>
      <value>40965</value>
      <webElementGuid>d68f251a-207d-4424-a722-a0c7aecad973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cb28cfa-05c3-41ca-a386-182ce512d44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parentfolder</name>
      <type>Main</type>
      <value>Salespage</value>
      <webElementGuid>22ba1824-67f4-4ac7-a893-01b54ba90a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mainfolder</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>8462c04f-a433-461c-9a99-02926b5766c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-childfolder</name>
      <type>Main</type>
      <value>ASalesPage</value>
      <webElementGuid>435ea443-7c66-4207-b39b-30ebc3a9b89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatetypeid</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>67cb9d19-8816-4efc-b900-14aff47fef98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-funnelid</name>
      <type>Main</type>
      <value>40485</value>
      <webElementGuid>4734910c-da52-4047-a0f9-20eeccef835a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatefilename</name>
      <type>Main</type>
      <value>Template.html</value>
      <webElementGuid>4bd59dc3-4e54-4506-9c62-2f907ee53e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>d0f2bbbb-b7db-437c-a137-08967d263322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1c822190-a51c-4669-b183-d0f6fa8c163b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>c5153c27-7b66-4fa0-a391-14fd5034dfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-1 btn-outline-primary templates</value>
      <webElementGuid>5305c0c0-6efb-47aa-8e8d-e3ac4c8245d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Use This</value>
      <webElementGuid>ba5a5b62-6d01-46e2-9ce9-776d8792066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vertical-layout h-100 vertical-menu-modern menu-expanded navbar-floating footer-static&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content-body&quot;]/section[1]/div[@class=&quot;b-overlay-wrap position-relative loaderPreview&quot;]/div[3]/div[@class=&quot;row match-height&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;custom-col-6 col-lg-4&quot;]/div[@class=&quot;card shadow-none&quot;]/div[@class=&quot;row text-center mx-0&quot;]/div[@class=&quot;border-top d-flex align-items-between flex-column py-1 col-12&quot;]/h3[@class=&quot;font-weight-bolder mb-0&quot;]/a[@class=&quot;btn mr-1 btn-outline-primary templates&quot;]</value>
      <webElementGuid>8b31c040-07f5-4a77-9a3d-ae4d8287f666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[3]/div/section/div/div[3]/div/div/div/div/div/div[2]/div/h3/a</value>
      <webElementGuid>00ec88e0-54ef-446a-98f6-34b962c1233a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sales'])[1]/following::a[5]</value>
      <webElementGuid>d72244bf-dad2-41ee-a1ba-d233471f8079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::a[5]</value>
      <webElementGuid>18a5ea5b-2ef5-4acc-b4d6-c24b5d2c9bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::a[1]</value>
      <webElementGuid>2651bdbc-9056-4458-8a13-2cf3b918316f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>f7a3840e-0b45-4c0d-86c1-0d515dad8a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>0581f3f9-882b-4816-aa07-04be29aea08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Use This' or . = 'Use This')]</value>
      <webElementGuid>3edd53f8-df49-4a33-b8df-59b819b08c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
