<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ProductName</name>
   <tag></tag>
   <elementGuidId>421147dd-033d-46c7-9877-e7decf7521c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ProductName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>097d0b54-12cc-4ce6-ba36-a25704b8a017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>7032b2ef-cf6e-4631-ac0f-7d77c2c80d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>d2d083c7-0a23-4ed1-906f-765dd0d02bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee429714-f20d-43e7-b602-c44c38a180f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Product Name</value>
      <webElementGuid>55bad9de-f446-4c2d-90d0-6b8ced0a855f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3e44ad36-24a5-4a31-a0e2-12cfef396c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductName&quot;)</value>
      <webElementGuid>d1ae785a-5de9-4f58-b0ff-b3b736ee7eb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductName']</value>
      <webElementGuid>a7b09b75-2b97-4ccf-a6c0-f8d69bddcd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__481']/div/span/input</value>
      <webElementGuid>31d641a0-0a35-454b-99af-70197c422780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>972c5b65-e345-4764-95af-130425ecb398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductName' and @name = 'ProductName' and @type = 'text' and @placeholder = 'Please Enter Product Name']</value>
      <webElementGuid>41e3b8d7-1976-4c59-ba71-8cbfb9426340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
