<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Payment Method PayPal  Stripe_d0e314</name>
   <tag></tag>
   <elementGuidId>fa18dd43-4373-486a-bc91-75609ba93a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PaymentMethodId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PaymentMethodId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7d4566cd-ccd9-4837-91ac-430ba3355053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaymentMethodId</value>
      <webElementGuid>21cba313-e106-4d76-8235-b742caaf4ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaymentMethodId</value>
      <webElementGuid>2cb193f7-7c03-4ac3-8ea7-92a3adae00df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ab6a2e12-b731-4747-8f34-cb9fc921f5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Payment Method PayPal  Stripe  Authorize Net </value>
      <webElementGuid>ec1da940-8301-4ad9-ba06-8f156ff7ed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymentMethodId&quot;)</value>
      <webElementGuid>f4061c8c-905e-4bd0-9fc9-9c9e55845573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PaymentMethodId']</value>
      <webElementGuid>5288eca2-87d8-42ff-bf53-012b847bd42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__487']/div/span/select</value>
      <webElementGuid>ee2576ba-446f-4727-b928-e4c3b3049e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>f6e90cce-b22b-4fef-b933-bc2465cc76fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Archived'])[1]/preceding::select[1]</value>
      <webElementGuid>aa84d2e9-758c-460f-9575-46934e9505f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[1]</value>
      <webElementGuid>adb6f587-8fea-4956-8944-b016618481e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>1a01e9f4-3c26-41dc-a0cf-cf40230499be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PaymentMethodId' and @id = 'PaymentMethodId' and (text() = 'Select Payment Method PayPal  Stripe  Authorize Net ' or . = 'Select Payment Method PayPal  Stripe  Authorize Net ')]</value>
      <webElementGuid>da4fa552-7427-45c2-8c15-fe999ce76c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
