<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__new-password</name>
   <tag></tag>
   <elementGuidId>768b73ed-15a4-416c-b15d-94f9a02e7736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-new-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account-new-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>168d716d-4b2d-46a6-8a92-d1ee7ad9d6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-new-password</value>
      <webElementGuid>16736a15-8eff-409f-9169-f65f4f2f16d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>8badba28-d2bd-45f6-a6fa-c8f56907df9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e2d300a2-bf81-4c37-b659-20ffe0c0d91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New Password</value>
      <webElementGuid>4a8649cd-4a42-471c-8aa7-76ac941736dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dd8383af-f976-49cc-8257-7bfba8a98648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-new-password&quot;)</value>
      <webElementGuid>88c2d745-6014-4770-a9a5-c41dbd8cf593</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account-new-password']</value>
      <webElementGuid>7b6a9405-51af-41ba-978c-6f8ddc244318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__154']/div/span/div/input</value>
      <webElementGuid>540c6507-bc56-44c4-ae0b-626cb26e9f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset/div/span/div/input</value>
      <webElementGuid>11872288-c2be-4af8-822e-42227b4b4ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'account-new-password' and @name = 'new-password' and @type = 'password' and @placeholder = 'New Password']</value>
      <webElementGuid>1c2c529a-a2d2-4998-a7e0-6f6f318bdb8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
