<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__retype-password</name>
   <tag></tag>
   <elementGuidId>8b906560-1751-43fc-9113-f8132b14a9b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-retype-new-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account-retype-new-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b70276c-7626-4083-9ec2-5aee493f821c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-retype-new-password</value>
      <webElementGuid>353a362f-f0f1-4adc-b99e-2391dfc57653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>retype-password</value>
      <webElementGuid>92202cd5-6423-47d1-a4bc-e644c9224e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>68f3308a-30b4-4b55-8a30-1c68218f3476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New Password</value>
      <webElementGuid>054eec61-290b-4a32-ad92-04e28df7ccd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>379e2897-ac62-49c6-9922-589fc2504981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-retype-new-password&quot;)</value>
      <webElementGuid>5fa58c89-ae23-48a9-93ef-a715f7f72fde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account-retype-new-password']</value>
      <webElementGuid>b6b30f67-1324-4669-afde-eac784404788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__157']/div/span/div/input</value>
      <webElementGuid>723eb3b2-2385-444b-8344-c13c17c50c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div/span/div/input</value>
      <webElementGuid>222f6119-c9b1-4f85-8a64-60653beff94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'account-retype-new-password' and @name = 'retype-password' and @type = 'password' and @placeholder = 'New Password']</value>
      <webElementGuid>d8e7759e-dc77-49e2-8b89-5d1f5679ae8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
