<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__old-password</name>
   <tag></tag>
   <elementGuidId>903ba8cf-dcc9-49e5-b338-f7940b314945</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-old-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account-old-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96434291-bac9-4e8d-af4b-fbf0e2a2ef4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-old-password</value>
      <webElementGuid>239ce99b-9489-41c1-af78-0e08792f2b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>old-password</value>
      <webElementGuid>cf0683fe-c5a9-431e-bbf5-a34eaebe24ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7d4ec4bb-43eb-48fd-b5ba-4dd35f1e69b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Current Password</value>
      <webElementGuid>92b98274-56e4-40fa-b3a8-c9795f69aaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc589484-408e-42d2-a94c-9b1365c5bac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-old-password&quot;)</value>
      <webElementGuid>8f605be7-201f-474f-96a1-e44525fc0286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account-old-password']</value>
      <webElementGuid>6af8ee8f-9aa2-497b-8690-c38eb172320e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__151']/div/span/div/input</value>
      <webElementGuid>7bba003c-84ca-434c-bca0-f72ffd128360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>ca8e701f-6fea-4cd8-bd8c-a675fbbf991f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'account-old-password' and @name = 'old-password' and @type = 'password' and @placeholder = 'Current Password']</value>
      <webElementGuid>66eb5ace-c5e7-433e-a091-36740d2b309f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
