<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a4b55993-9488-45c9-ac4c-0b3594723582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;avatar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1641234b-d05f-49d7-9f4f-c6e8f85925b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/3408640b-defb-4567-8249-072c08ff3ec1.png</value>
      <webElementGuid>7b25d8b5-dd39-44da-9ab4-7ef270957f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>ada7ea14-a5fb-4dc6-a09f-055d48a7cf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarimage&quot;)/span[@class=&quot;b-avatar-img&quot;]/img[1]</value>
      <webElementGuid>63b8cee5-143c-49df-b191-fca3a07acf2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbarimage']/span/img</value>
      <webElementGuid>6bc6142d-05fe-48d0-9345-f2d822643119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>a0293d0d-794c-48e6-a856-7c80112a843c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>76adc203-2d49-4687-a350-173449f753ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/3408640b-defb-4567-8249-072c08ff3ec1.png' and @alt = 'avatar']</value>
      <webElementGuid>d93bd0ba-9675-4f84-ba7c-b50d1b832ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
