<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Use This</name>
   <tag></tag>
   <elementGuidId>bb14c968-b1bd-402f-bf36-b91d3867bc3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.mr-1.btn-outline-primary.templates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/div/div/div[2]/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>702bb18d-e01a-4324-a0da-45e6af2b6c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-userstepid</name>
      <type>Main</type>
      <value>40965</value>
      <webElementGuid>4495d9ef-5e7c-48ed-a7f3-9694cc8d4877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currenttabid</name>
      <type>Main</type>
      <value>40965</value>
      <webElementGuid>a79a80f1-1de0-4704-8937-c00b88c3483f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>19c8a6fb-ae99-4f79-9be3-a582d57faa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parentfolder</name>
      <type>Main</type>
      <value>Salespage</value>
      <webElementGuid>2bb5c0ca-c105-48fa-8a47-cebd27b7c219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mainfolder</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>ec92c3c8-bedf-4a3c-83ae-1ca69f646245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-childfolder</name>
      <type>Main</type>
      <value>ASalesPage</value>
      <webElementGuid>57a00704-052f-4b2b-a380-bd7d675c1b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatetypeid</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>877df9da-52c7-460d-8b50-bb46e0813ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-funnelid</name>
      <type>Main</type>
      <value>40485</value>
      <webElementGuid>5aa894d3-e5d7-407c-b821-9e7a6eff7308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatefilename</name>
      <type>Main</type>
      <value>Template.html</value>
      <webElementGuid>c34d9d15-ee17-44b8-824c-394cf086035d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>87cb1675-8671-4b1d-90c5-41c540e3289c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b49c87c6-527b-40b2-b6af-ab1738503825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>7c0abaa6-67ff-4152-a164-8f7ecf4fcc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-1 btn-outline-primary templates</value>
      <webElementGuid>75c17890-b55f-4653-aeb6-d4a32abfa2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Use This</value>
      <webElementGuid>72c205b8-b3a2-443d-9b81-b79268c7aa61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vertical-layout h-100 vertical-menu-modern menu-expanded navbar-floating footer-static&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content-body&quot;]/section[1]/div[@class=&quot;b-overlay-wrap position-relative loaderPreview&quot;]/div[3]/div[@class=&quot;row match-height&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;custom-col-6 col-lg-4&quot;]/div[@class=&quot;card shadow-none&quot;]/div[@class=&quot;row text-center mx-0&quot;]/div[@class=&quot;border-top d-flex align-items-between flex-column py-1 col-12&quot;]/h3[@class=&quot;font-weight-bolder mb-0&quot;]/a[@class=&quot;btn mr-1 btn-outline-primary templates&quot;]</value>
      <webElementGuid>d9908c95-db2a-453d-921b-5e342f15be13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[3]/div/section/div/div[3]/div/div/div/div/div/div[2]/div/h3/a</value>
      <webElementGuid>0526d235-53c0-4132-9143-f9f6ff5c53b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sales'])[1]/following::a[5]</value>
      <webElementGuid>089b2584-4488-48a5-ac84-f20964fa438c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::a[5]</value>
      <webElementGuid>ccb3f117-369a-474f-9e6f-3f6e33777b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::a[1]</value>
      <webElementGuid>2f06e4a9-9441-420c-b2d7-cdcb32e0cda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>ecb2fa1d-e6ee-4699-baa7-285093a2f3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>0c2b7687-2ddd-4d95-ad53-01ff74f7705d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Use This' or . = 'Use This')]</value>
      <webElementGuid>9cf7d77a-01ed-4806-8920-658eefaa74a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
