<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ProductName</name>
   <tag></tag>
   <elementGuidId>aabfa614-1aca-401a-9bd5-d9574712f92e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db62ca64-31b0-4903-bd6d-e082cdd6de8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>db5ef644-eceb-4e59-8465-74c301c2e347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>f0c57fda-4aa6-466d-9c86-935965185d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e2c13b6-e5bc-44c8-bfce-fc6a84e15cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Product Name</value>
      <webElementGuid>f0486adb-3732-440c-9c27-eca2c0f88cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b4b4a614-d747-498e-9d6d-285d754e798f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductName&quot;)</value>
      <webElementGuid>45b2b4c0-b90d-4e2e-a12c-2a83641cac6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductName']</value>
      <webElementGuid>14223f37-2c48-4863-9697-39c210cc77cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__481']/div/span/input</value>
      <webElementGuid>4cf41157-d30a-4cd4-8e15-8b1d9721c4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8ad94da5-2bf9-4315-86e0-f0f6d12b6a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductName' and @name = 'ProductName' and @type = 'text' and @placeholder = 'Please Enter Product Name']</value>
      <webElementGuid>4c8d14e8-2164-46bb-8aca-97856e41e466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
