<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ProductPrice</name>
   <tag></tag>
   <elementGuidId>36f8a45e-947a-4371-bc2d-c9c7636e6673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>735005f0-9ebb-4be1-ba5d-6fec58900b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductPrice</value>
      <webElementGuid>eb812afc-1fa8-412f-bf38-1abc60191dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductPrice</value>
      <webElementGuid>828d4685-35a2-41d6-854a-27ba139f6d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c4050e7-229a-45ca-86c5-0559105ad469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Product Price</value>
      <webElementGuid>fc1c0981-1552-42c4-850f-1d371b893e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08555dde-1c78-4e28-90c9-8f9dfb3075ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductPrice&quot;)</value>
      <webElementGuid>5a275c56-a4c8-4aed-b7b3-79754eecd512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductPrice']</value>
      <webElementGuid>b7ac0962-bc78-4211-9ec0-8d81cb3f7054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__484']/div/span/div/input</value>
      <webElementGuid>b55388dc-dc3c-411f-a8d7-fd7c6d510b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>f0632bc6-75d2-4453-80b1-9e8547d79ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductPrice' and @name = 'ProductPrice' and @type = 'text' and @placeholder = 'Please Enter Product Price']</value>
      <webElementGuid>d4b56629-f978-4b81-bae3-73052c4cfc31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
