<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Payment Method PayPal  Stripe_d0e314</name>
   <tag></tag>
   <elementGuidId>0aab3913-158a-4c3d-9305-eff1be3a3f41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PaymentMethodId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PaymentMethodId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>77d31a8e-35fd-4c59-8985-25c8123524d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaymentMethodId</value>
      <webElementGuid>b21d8b55-28fb-46ca-9e7a-5325757e5966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaymentMethodId</value>
      <webElementGuid>7eea8790-e10b-4700-b879-4435a7ed68ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2d820268-f6e2-48b0-8bb0-ece78bb6b4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Payment Method PayPal  Stripe  Authorize Net </value>
      <webElementGuid>04850f48-9f0c-42dd-8a0d-d5bf963ccfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymentMethodId&quot;)</value>
      <webElementGuid>2734f62c-e5e0-4730-96bd-773f5fa56a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PaymentMethodId']</value>
      <webElementGuid>c0eb481e-ad04-4634-8be1-5303d29fa6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__487']/div/span/select</value>
      <webElementGuid>499ff6e2-4b17-4ea5-96f2-24faff28967a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>d4abadbf-26d0-4640-94a5-fd7c5c74e174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Archived'])[1]/preceding::select[1]</value>
      <webElementGuid>b2963d82-7a6f-4741-bd17-f5839a8d17d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[1]</value>
      <webElementGuid>0c1a869d-4284-4a41-9e32-c032cef789a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>13f47bd0-f75b-4853-83e6-d322845b4adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PaymentMethodId' and @id = 'PaymentMethodId' and (text() = 'Select Payment Method PayPal  Stripe  Authorize Net ' or . = 'Select Payment Method PayPal  Stripe  Authorize Net ')]</value>
      <webElementGuid>eb512788-2a75-4816-bef8-7ed304464c72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
