<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Use This</name>
   <tag></tag>
   <elementGuidId>f6631cd0-b039-4477-a00c-c3268c6fe26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div[3]/div/section/div/div[3]/div/div/div/div/div/div[2]/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.mr-1.btn-outline-primary.templates</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3337d1eb-54b4-4824-82e1-e7600d5d2131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-userstepid</name>
      <type>Main</type>
      <value>40963</value>
      <webElementGuid>9be4ae3c-bfe6-45ff-bf97-a909ff762140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-currenttabid</name>
      <type>Main</type>
      <value>40963</value>
      <webElementGuid>b83ca62c-9436-4987-9ba8-6c95a0b697be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72cf59ae-f819-477b-b277-76e91c5b8cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parentfolder</name>
      <type>Main</type>
      <value>Salespage</value>
      <webElementGuid>080fd7ce-0a62-4de2-9345-1fc0a149ef09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mainfolder</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>e315d8af-b8ef-4f78-90b1-08ec61bd0956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-childfolder</name>
      <type>Main</type>
      <value>ASalesPage</value>
      <webElementGuid>f2579baa-3c3e-4264-9651-593f392c3895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatetypeid</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>a0bc149a-966b-4a92-b49f-72b389535e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-funnelid</name>
      <type>Main</type>
      <value>40484</value>
      <webElementGuid>abc58ee1-cd8e-4809-88b8-68d074bf2c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-templatefilename</name>
      <type>Main</type>
      <value>Template.html</value>
      <webElementGuid>5123be66-2cef-4341-a4c2-df589eab083d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>4f4c5a1b-ce0f-41ea-947d-aeca900e9ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8d07ea41-5119-4167-ace7-0e631557372f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>6434e46c-8e42-4381-9bb3-baeee7135ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mr-1 btn-outline-primary templates</value>
      <webElementGuid>dc3cde18-ac93-404b-b4f8-c0a3f5337c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Use This</value>
      <webElementGuid>917f4cb9-14dc-423d-8fa8-3689b59c6525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;vertical-layout h-100 vertical-menu-modern menu-expanded navbar-floating footer-static&quot;]/div[@class=&quot;app-content content&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content-body&quot;]/section[1]/div[@class=&quot;b-overlay-wrap position-relative loaderPreview&quot;]/div[3]/div[@class=&quot;row match-height&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;custom-col-6 col-lg-4&quot;]/div[@class=&quot;card shadow-none&quot;]/div[@class=&quot;row text-center mx-0&quot;]/div[@class=&quot;border-top d-flex align-items-between flex-column py-1 col-12&quot;]/h3[@class=&quot;font-weight-bolder mb-0&quot;]/a[@class=&quot;btn mr-1 btn-outline-primary templates&quot;]</value>
      <webElementGuid>f574d598-d9bb-4d42-bd9f-4846830ef4ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div[3]/div/section/div/div[3]/div/div/div/div/div/div[2]/div/h3/a</value>
      <webElementGuid>65083b51-0d3a-4dde-8e8a-57adaf255c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sales project'])[1]/following::a[6]</value>
      <webElementGuid>e0af2556-60fb-499f-a74c-8b9a4a0626de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[2]/following::a[6]</value>
      <webElementGuid>4b11d2f4-fb24-4119-82ba-dabbdb676caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::a[1]</value>
      <webElementGuid>1feeb3cf-7590-4944-ab53-e95587fb1223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>2f01b732-f4d7-4ec0-973a-7eed47b9c5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>6506b1e2-11fb-49e8-be69-d04a1cb2aa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Use This' or . = 'Use This')]</value>
      <webElementGuid>228b09f3-1358-422f-8486-837bc9e402d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
