<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ProductName</name>
   <tag></tag>
   <elementGuidId>1754c9ec-e59b-4737-97bc-40fdad8a0135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>881f6e1c-1e4e-4a09-894a-624663ee1aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>e1d22ff9-adf3-4e33-9bc2-c4dc83e50ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductName</value>
      <webElementGuid>dabd6a92-bffb-45a5-b8f8-ecdd13fa393a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e18fc5c-9684-4601-8a4b-6e58c6ad7c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Product Name</value>
      <webElementGuid>9f92de7c-b014-4096-98f3-616f51515438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0b458c76-512b-4b23-8b64-c04cd22820f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductName&quot;)</value>
      <webElementGuid>30f84a68-add0-4c3e-9c30-904a88104f6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductName']</value>
      <webElementGuid>ffce4714-0965-47da-b53b-bb4df678e797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__481']/div/span/input</value>
      <webElementGuid>d28b7efc-51f8-4cbc-9f62-7a359f12940a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f16ac929-6d32-4b43-a328-454e008cfd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductName' and @name = 'ProductName' and @type = 'text' and @placeholder = 'Please Enter Product Name']</value>
      <webElementGuid>88015628-bea6-42fd-be77-5ac5ec5b6f22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
