<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ProductPrice</name>
   <tag></tag>
   <elementGuidId>ac3a9446-58b8-40e7-b448-ff2adca84aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductPrice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductPrice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>531dccd0-2dec-4aa8-b04f-98c7f44fbc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductPrice</value>
      <webElementGuid>de499236-c7dd-4f6a-8290-cf7d48c72480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductPrice</value>
      <webElementGuid>fa14c232-97ab-493a-b223-467e8646dc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb271110-beba-4bf1-bdf6-cb33a4330e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Product Price</value>
      <webElementGuid>52fe4904-d02b-4a4f-8331-6e841f5092b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>47eb2166-a45e-43e8-8159-3192a4c5f715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductPrice&quot;)</value>
      <webElementGuid>1ed564cb-3821-4c26-a350-64fb3b6cf4bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductPrice']</value>
      <webElementGuid>7c80f209-2882-4811-9ae3-eeb6e6a7a100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__484']/div/span/div/input</value>
      <webElementGuid>0b1425b5-2707-4f06-a1d2-0897624de9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>b549cc50-7e4b-49c1-8ed4-8cc0426a5a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductPrice' and @name = 'ProductPrice' and @type = 'text' and @placeholder = 'Please Enter Product Price']</value>
      <webElementGuid>8e567de1-ca57-4ee0-b106-595daa36f558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
