<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Payment Method PayPal  Stripe_d0e314</name>
   <tag></tag>
   <elementGuidId>a2dbc928-a62b-47c6-a7ab-efd4d03b6122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PaymentMethodId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PaymentMethodId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fcf30d41-bf26-4a59-9792-94e0da8affed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PaymentMethodId</value>
      <webElementGuid>e9ab757a-7418-4f69-97eb-d7b514fecac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PaymentMethodId</value>
      <webElementGuid>acc038ca-a382-40da-80ad-42e10287446f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06e317f2-5b4e-4073-9fb2-cc48ff7b45b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Payment Method PayPal  Stripe  Authorize Net </value>
      <webElementGuid>822b35b6-b3a6-4ac6-9ca8-a6d23e731469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PaymentMethodId&quot;)</value>
      <webElementGuid>5fe70f43-3269-401e-8558-832b0453e555</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PaymentMethodId']</value>
      <webElementGuid>bb327e3e-5291-47e6-83fd-11afbd7d6025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__487']/div/span/select</value>
      <webElementGuid>7bf6c8d7-8629-49ef-9f2b-97488ca166e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>d49ad0e0-8312-4709-b13e-abcfe176c154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Archived'])[1]/preceding::select[1]</value>
      <webElementGuid>aced5fea-c1c9-41c5-b071-4855a51908c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::select[1]</value>
      <webElementGuid>fc874db3-d8f7-4a01-bb3e-454a1bfb0773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/select</value>
      <webElementGuid>18296c63-7572-4f83-8910-91be789ef6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'PaymentMethodId' and @id = 'PaymentMethodId' and (text() = 'Select Payment Method PayPal  Stripe  Authorize Net ' or . = 'Select Payment Method PayPal  Stripe  Authorize Net ')]</value>
      <webElementGuid>2c67cbf2-f5d2-498f-a5d1-c4eec7848e7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
