<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1be91ba6-e290-400b-a091-26b01b017b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;avatar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navbarimage']/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9cea1c88-9553-4405-becb-ddccbdf2d279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/87f1d2a0-94c4-4e1f-b3d7-91e2910d0806.png</value>
      <webElementGuid>7ed08e89-5c3e-4e55-9f99-94137964ec6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>74591102-001e-4641-8a7d-aad33c670b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarimage&quot;)/span[@class=&quot;b-avatar-img&quot;]/img[1]</value>
      <webElementGuid>5a79a34b-5af0-485f-a8c6-81aa81dae50e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbarimage']/span/img</value>
      <webElementGuid>bf39c9b9-4e3b-4591-a3ef-8ef144d231a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>68cf54b9-3575-4efe-ab08-d59ee938192b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>0a4b678b-ed33-4489-b5a1-90ad9b866c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/87f1d2a0-94c4-4e1f-b3d7-91e2910d0806.png' and @alt = 'avatar']</value>
      <webElementGuid>87675554-7fc2-4641-9b81-a1964db6d144</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
