<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1be91ba6-e290-400b-a091-26b01b017b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;avatar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1cd7b856-929c-4b96-8c75-2fd4e2d87fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/87f1d2a0-94c4-4e1f-b3d7-91e2910d0806.png</value>
      <webElementGuid>2ebf51ff-5d22-4ac2-8a45-b974f0e4f916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>aa8bbbe0-fecc-4b67-8426-aa2ed7595fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarimage&quot;)/span[@class=&quot;b-avatar-img&quot;]/img[1]</value>
      <webElementGuid>46df9f85-7cc3-4765-9764-4ef3e5568576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navbarimage']/span/img</value>
      <webElementGuid>77481761-ced6-45f2-b2b7-b0e26af4c1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>17111e49-7d16-4bac-be71-3094aeb9dd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>49c1351b-4953-4a71-a5ce-66a8bffb133a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.landingly.com/Images/ProfilePics/3def73ec-074c-4973-a741-1b7a0673b606/87f1d2a0-94c4-4e1f-b3d7-91e2910d0806.png' and @alt = 'avatar']</value>
      <webElementGuid>0f528948-b5aa-463a-85ed-ce954ca6a958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
