<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Build Project</name>
   <tag></tag>
   <elementGuidId>4da718fb-d4d7-4f29-b785-52d27b581f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnGoalOneStep</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnGoalOneStep']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59576a2e-770b-46d6-99a2-f2ec4eda3779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGoalOneStep</value>
      <webElementGuid>1a72fb97-0271-49e3-aa2d-94c29e39274e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>751f71e5-3867-482a-87be-ca169b37c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>070881ff-68b7-4e3a-9a33-e669640da327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Build Project </value>
      <webElementGuid>0e5487b6-5632-46b4-b063-56750d264172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGoalOneStep&quot;)</value>
      <webElementGuid>2d831ceb-875c-46e3-8e93-a44d48f04f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnGoalOneStep']</value>
      <webElementGuid>6be68275-a76d-49a4-9a06-b0c26cf388f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='addProjModal___BV_modal_footer_']/button[2]</value>
      <webElementGuid>0b1a765a-4a6f-4053-91f1-7fe3417b0840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>474f0045-d3c9-4119-aa74-2dafee37f218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell your products after collecting leads with a squeeze page.'])[1]/following::button[2]</value>
      <webElementGuid>e1d25ec6-7350-48fa-bc82-60595983f4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Build Project']/parent::*</value>
      <webElementGuid>057c7073-4d9f-48c5-b426-2955b867a528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]</value>
      <webElementGuid>8e22b12e-3441-4ec9-a6d5-513a676c0b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnGoalOneStep' and @type = 'button' and (text() = ' Build Project ' or . = ' Build Project ')]</value>
      <webElementGuid>8f2be7d9-85d2-4bb6-9f85-98ed3a329f2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
