<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mailbody</name>
   <tag></tag>
   <elementGuidId>2155c213-e6ea-4d71-9b59-3b45d2230951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[6]/div/div/div/div/span/form/div/div/div[9]/fieldset/div/span/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CamSpam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>107d1626-e11a-49fa-b910-8de719e5571d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CamSpam</value>
      <webElementGuid>b53a6ea8-3591-4626-9b02-146e4a17b139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CamSpam</value>
      <webElementGuid>eebf42ad-1b92-48d9-882c-b77ae0505e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a6c45e2-d6b9-43d8-9cfb-e9b86400fd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give CamSpam...</value>
      <webElementGuid>ff41e771-81a0-45e3-96ff-c0e1e0fb657f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc87f8c2-3e95-4817-a7d9-b2a1d5f4d269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CamSpam&quot;)</value>
      <webElementGuid>a349495a-5352-46e7-b52b-24fc7567823d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CamSpam']</value>
      <webElementGuid>af3f74d8-702c-4da5-9baa-a11227f3da6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__490']/div/input</value>
      <webElementGuid>be02d89e-467c-4f54-bfc5-344044c1ed5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>84d8b9ea-6751-4448-b7bf-b2cdf73770fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CamSpam' and @name = 'CamSpam' and @type = 'text' and @placeholder = 'Give CamSpam...']</value>
      <webElementGuid>dc7f0611-8a7c-4aa8-9e09-ebcd790d1c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
