<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ReplyToEmail</name>
   <tag></tag>
   <elementGuidId>734f4650-3add-4c64-9d13-4f7246602491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReplyToEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReplyToEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52736a04-9bf1-4fd8-8604-3213e2e37c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReplyToEmail</value>
      <webElementGuid>078e40ac-2ca7-41ec-adad-871855356ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReplyToEmail</value>
      <webElementGuid>be2d1ea3-175e-4d2d-9313-e3900170af4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d1707be-8d22-47a2-a4d7-a041e214d9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Reply To Email</value>
      <webElementGuid>9061bfd4-3b66-4c39-87f4-48e8a032abed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2c95de55-cc9a-4abf-9789-129712f0f845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReplyToEmail&quot;)</value>
      <webElementGuid>c0b345ea-5bfa-401a-bfc2-b61b66b8eb09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReplyToEmail']</value>
      <webElementGuid>f9cb955f-cfc7-4a43-8fbf-3cfc20bf1372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__480']/div/span/input</value>
      <webElementGuid>e05bc110-f7fe-4ed0-a7fc-3dc0b0cf6edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/span/input</value>
      <webElementGuid>ef6219e5-c503-4f1d-bdc3-c487c3e2d722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReplyToEmail' and @name = 'ReplyToEmail' and @type = 'text' and @placeholder = 'Please Enter Reply To Email']</value>
      <webElementGuid>d299ebad-9568-43a5-9a3b-272ad7cc216e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
