<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mailbody</name>
   <tag></tag>
   <elementGuidId>2155c213-e6ea-4d71-9b59-3b45d2230951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[5]/div/div/div/div/span/form/div/div/div[9]/fieldset/div/span/div/div[2]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CamSpam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac6fa960-d8c4-4bd1-bc1f-c6e2200e65c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CamSpam</value>
      <webElementGuid>3bc65eab-1a67-45bd-9aa1-1e049376a246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CamSpam</value>
      <webElementGuid>3293709f-3bcb-48ce-81c0-18ce93a13c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1856c39-62e5-4a87-adae-0ccbeaa286f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give CamSpam...</value>
      <webElementGuid>5a9862d6-4869-48b5-86bf-a205413f4ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c2580547-3175-451a-ae7d-ef97b1d2fd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CamSpam&quot;)</value>
      <webElementGuid>a21f6cd0-10c8-42e5-a4da-ea5b849bc162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CamSpam']</value>
      <webElementGuid>dc20411b-ea6b-43f0-8935-930eab034a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__490']/div/input</value>
      <webElementGuid>378df2e8-f092-4ee8-9da0-f21af3e780df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>a71d9242-dd1d-4c64-9ee2-580e57d3033f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CamSpam' and @name = 'CamSpam' and @type = 'text' and @placeholder = 'Give CamSpam...']</value>
      <webElementGuid>080075f6-9871-4d2d-b9aa-9e3092cb5ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
