<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__FromName</name>
   <tag></tag>
   <elementGuidId>a43b1e2b-ce8d-4890-b40d-b004f49eff53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FromName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FromName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f54aabd-e81f-4bad-b652-6d846f9eceb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FromName</value>
      <webElementGuid>4cb2071e-6606-42e2-80c8-31b898aea2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FromName</value>
      <webElementGuid>be085546-ce37-4b49-b3fc-0c0171d2d451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b83ab9f-248e-485f-84eb-2ce814f72c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter From Name</value>
      <webElementGuid>9db694b7-c5c4-4974-b0d5-7856f8b371b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>361f35ab-af99-487f-85af-26011d72211a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FromName&quot;)</value>
      <webElementGuid>796d0fb8-5ed3-4715-8f20-c3a4eeed7148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FromName']</value>
      <webElementGuid>bef172df-2f2c-44b7-9dd6-2bf74f9cc32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__474']/div/span/input</value>
      <webElementGuid>01127b1e-7b2a-4677-bff8-f56deb462955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>256395f3-cc42-46c6-b28d-983c14b0d31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FromName' and @name = 'FromName' and @type = 'text' and @placeholder = 'Please Enter From Name']</value>
      <webElementGuid>1853af5c-614e-4a3c-b0f3-22dc402e0e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
