<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cam Spam_CamSpam</name>
   <tag></tag>
   <elementGuidId>8a548bae-88cf-4fca-8569-0cc7a2765262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CamSpam']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CamSpam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddd11681-e360-49d0-9bd1-f707976a74be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CamSpam</value>
      <webElementGuid>ed1e442e-747f-442e-a849-efa339425f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CamSpam</value>
      <webElementGuid>8c3ef720-3cd1-4c2c-8a2b-3af9145df0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>212ed3a2-d904-4f78-a7b9-d22ee21bc668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Give CamSpam...</value>
      <webElementGuid>44a55880-c565-42b1-a53e-92019b7775ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c59b2baf-47ea-44a0-ab50-a39c801ba4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CamSpam&quot;)</value>
      <webElementGuid>b27d7754-fd0f-4e25-a206-875dcd75f81d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CamSpam']</value>
      <webElementGuid>a6de9976-416e-4ee8-a38d-7b709f406945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__490']/div/input</value>
      <webElementGuid>5c900db7-1a42-4c52-9187-e5480f4d4a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>3304cdcf-974b-485a-b16f-d045d60f9a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CamSpam' and @name = 'CamSpam' and @type = 'text' and @placeholder = 'Give CamSpam...']</value>
      <webElementGuid>12bb4bd0-49a5-49dd-87d6-79f62c58a709</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
