<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Subject</name>
   <tag></tag>
   <elementGuidId>eafe9a15-a54e-4ea9-b283-9b1d5e8684f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Subject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Subject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52f2fbf8-c2c3-4501-a52f-977e1fa47c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>aec09bb0-8225-4cf6-8032-730aea314c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>ed69c62c-86db-4827-b956-4e61c308eab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>950c90b7-7387-4d1a-bd5a-ecda2cad3b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please Enter Email Subject</value>
      <webElementGuid>60925ad5-6a7c-472c-83a9-9b4a6182f802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>14955654-4fd9-4611-872c-60d5bc00c158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Subject&quot;)</value>
      <webElementGuid>e994c73c-4830-4c39-bbe8-8a1ec1040b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Subject']</value>
      <webElementGuid>89d531ff-90e0-4889-9bcb-772716cbcb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__477']/div/span/input</value>
      <webElementGuid>10563a07-71bc-4cc9-8411-4bb1aa62ffc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/span/input</value>
      <webElementGuid>30d5728b-e51e-472b-aed1-2b36bb7ee774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Subject' and @name = 'Subject' and @type = 'text' and @placeholder = 'Please Enter Email Subject']</value>
      <webElementGuid>59b525bc-df34-4210-8e23-6c6b98b0ad40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
