<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_login-email</name>
   <tag></tag>
   <elementGuidId>0a20588a-12d4-4e97-a69a-70e0aba9c3bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>871eeda9-6be0-45ac-8846-cdc869a3c13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-email</value>
      <webElementGuid>63a469ff-e971-4772-bb53-d2b01822e900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-email</value>
      <webElementGuid>8ec2d918-73b1-49e1-b68d-2b135de8309f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>52509a82-6207-45d1-a0e2-33663d0be362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>615b0dcb-e985-4216-9d66-bdbde15b63d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8c9a9496-11f9-4680-9ada-856013d4c2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-email&quot;)</value>
      <webElementGuid>91810425-ca2b-4b6e-9c5c-80a0ee637946</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-email']</value>
      <webElementGuid>ae725d9e-b3d5-41b7-be46-de9bef1ff9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__47']/div/span/input</value>
      <webElementGuid>99beffdc-a4a9-4289-9f4d-557f541e74d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>43ba334d-c58e-4f4b-ac10-67ab631ca366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-email' and @name = 'login-email' and @type = 'text' and @placeholder = 'email']</value>
      <webElementGuid>9785622a-ff5a-4642-9cbb-76a6c4291b6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
