<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Discover The 1 TrickFor Doubled Convers_94f5cb</name>
   <tag></tag>
   <elementGuidId>1ec9bfb1-abbb-429e-95a1-c91fe3cdc2f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sgi_143</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sgi_143']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40787c48-0312-447c-be83-22d7ecba7988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sgi_143</value>
      <webElementGuid>68254e94-59e0-4016-83cc-f9b9a001a3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ctrlWrapper imgContainer pgSingleImage</value>
      <webElementGuid>9de231ad-f070-41fd-ba1b-288131a456b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-link</name>
      <type>Main</type>
      <value>#no-link</value>
      <webElementGuid>093e9ef6-0e3c-4775-9d1b-15be8bd967af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sgi_143&quot;)</value>
      <webElementGuid>f6149736-322f-4c7e-8536-12f266343b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sgi_143']</value>
      <webElementGuid>23255c68-6093-48bd-8c67-323bc225cc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ele_299']/div/div</value>
      <webElementGuid>60437d51-d23d-465b-8da6-0c64eedcc7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discover The #1 TrickFor Doubled Conversions'])[1]/preceding::div[1]</value>
      <webElementGuid>489ba877-2ddc-4af7-b35c-000629a1f5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Your Copy Today'])[1]/preceding::div[4]</value>
      <webElementGuid>5e666ffa-aed7-4381-a8a9-33130a438dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>7a0473b4-92f0-4099-993a-4606b13c20d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sgi_143']</value>
      <webElementGuid>0b0fa5ec-c31b-46fc-80a5-1b0e1bead5ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
