<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_login-email</name>
   <tag></tag>
   <elementGuidId>1bd8fd7b-5d4d-490e-baa1-ced7d6d00f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20b49f93-5fa1-4355-b414-79c2a687f3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-email</value>
      <webElementGuid>1112b5d0-02c6-4209-8466-e2c682571337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login-email</value>
      <webElementGuid>d6d938a0-21fb-4f08-9187-0001c47a4688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d00f25c-15d7-4f1a-a681-9f04ddd37a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>469b20ac-dd43-42d5-9b8c-dd3c680c8c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ce584628-4731-4fa6-a8cd-7031beb35582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-email&quot;)</value>
      <webElementGuid>fbf7db54-e836-4c1e-b8d1-e9147d8e4f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login-email']</value>
      <webElementGuid>90e2e81b-2da6-4b58-b84a-6be9eb8db492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__47']/div/span/input</value>
      <webElementGuid>d7dd0e1f-b17a-48e6-9fb1-52d664ecf81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8467c0e8-db67-483e-98b5-4351d3b0d5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login-email' and @name = 'login-email' and @type = 'text' and @placeholder = 'email']</value>
      <webElementGuid>d11487e4-c84f-442f-83e7-2b629cc3cb9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
